# Makefile.toml
[config]
default_to_workspace = false # 启用工作空间支持

[tasks.release.windows]
script = '''
cmd /c copy /Y "target\release\cozy-lapce.exe" "C:\Users\36225\Desktop\"
'''
dependencies = ["_build-release"]

[tasks.run-dev]
script = '''
cargo run --bin cozy-lapce --no-default-features --features dev -- -w -n
'''
dependencies = ["_build-dev"]

[tasks._build-dev]
description = "Build the project"
command = "cargo"
args = ["build", "--features", "dev", "--no-default-features", "--bin", "cozy-lapce"]
[tasks._build-release]
command = "cargo"
args = ["build", "--release", "--bin", "cozy-lapce"]

[tasks.run-prod]
script = '''
cargo run --bin cozy-lapce -- -w -n
'''
dependencies = ["_build-prod"]
[tasks._build-prod]
description = "Build the project"
command = "cargo"
args = ["build", "--bin", "cozy-lapce"]
