#:schema ../extra/schemas/color-theme.json

[color-theme]
name = "Lapce Dark"

[color-theme.base]
black = "#282C34"
blue = "#61AFEF"
cyan = "#56B6C2"
green = "#98C379"
grey = "#3E4451"
magenta = "#C678DD"
orange = "#D19A66"
purple = "#C678DD"
red = "#E06C75"
white = "#ABB2BF"
yellow = "#E5C07B"

primary-background = "$black"
secondary-background = "#21252B"
current-background = "#2C313A"
text = "$white"
dim-text = "#5C6370"

[color-theme.syntax]
attribute = "$yellow"
"bracket.unpaired" = "$red"
builtinType = "$cyan"
comment = "$dim-text"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
"enum-member" = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
"markup.bold" = "$orange"
"markup.heading" = "$red"
"markup.italic" = "$orange"
"markup.link.label" = "$purple"
"markup.link.text" = "$purple"
"markup.link.url" = "$blue"
"markup.list" = "$orange"
method = "$blue"
number = "$yellow"
property = "$red"
"punctuation.delimiter" = "$yellow"
selfKeyword = "$purple"
string = "$green"
"string.escape" = "$cyan"
struct = "$yellow"
structure = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
variable = "$red"
"variable.other.member" = "$red"

selfTypeKeyword = "$blue"
macro = "#de712e"
builtinAttribute = "$blue"
boolean = "$blue"
const = "#a537a6"
lifetime = "#56abaa"
punctuation = "$purple"
operator = "$purple"
decorator = "$purple"

[color-theme.ui]
"activity.background" = "$secondary-background"
"activity.current" = "$primary-background"
"completion.background" = "$secondary-background"
"completion.current" = "$current-background"
"completion_lens.foreground" = "$dim-text"
"debug.breakpoint" = "$red"
"debug.breakpoint.hover" = "#E06C7566"
"editor.background" = "$primary-background"
"editor.caret" = "#528BFF"
"editor.current_line" = "#2C313C"
"editor.debug_break_line" = "#528abF37"
"editor.dim" = "$dim-text"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$text"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.sticky_header_background" = "$primary-background"
"editor.visible_whitespace" = "$grey"
"editor.bracket" = "#C5E1C5"
"editor.selection" = "#4c6b8f"
"editor.document_highlight" = "#eeebfc"

"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "$dim-text"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"

"hover.background" = "$secondary-background"
"lapce.border" = "#000000"
"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.icon.active" = "$text"
"lapce.icon.inactive" = "$dim-text"
"lapce.plugin.author" = "#B0B0B0"
"lapce.plugin.description" = "$text"
"lapce.plugin.name" = "#DDDDDD"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "$red"
"lapce.remote.icon" = "$black"
"lapce.remote.local" = "#4078F2"
"lapce.scroll_bar" = "#3E4451BB"
"lapce.tab.active.background" = "$primary-background"
"lapce.tab.active.foreground" = "$text"
"lapce.tab.active.underline" = "#528BFF"
"lapce.tab.inactive.background" = "$secondary-background"
"lapce.tab.inactive.foreground" = "$text"
"lapce.tab.inactive.underline" = "#528BFF77"
"lapce.warn" = "$yellow"

"markdown.blockquote" = "#898989"
"palette.background" = "$secondary-background"
"palette.current.background" = "$current-background"
"palette.current.foreground" = "$text"
"palette.foreground" = "$text"
"panel.background" = "$secondary-background"
"panel.current.background" = "$current-background"
"panel.current.foreground" = "$text"
"panel.current.foreground.dim" = "$dim-text"
"panel.foreground" = "$text"
"panel.foreground.dim" = "$dim-text"
"panel.hovered.active.background" = "$dim-text"
"panel.hovered.background" = "#343A45"
"panel.hovered.foreground" = "$text"
"panel.hovered.foreground.dim" = "$dim-text"

"source_control.added" = "#50A14FCC"
"source_control.modified" = "#0184BCCC"
"source_control.removed" = "#FF5266CC"

"status.background" = "$secondary-background"
"status.foreground" = "$text"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"

"terminal.background" = "$primary-background"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$text"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$text"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

"tooltip.background" = "$primary-background"
"tooltip.foreground" = "$text"

"inlay_hint.background" = "#2C313C"
"inlay_hint.foreground" = "$dim-text"

[ui]
drop-shadow-width = 0
font-family = ""
font-size = 13
header-height = 35
hover-font-family = ""
hover-font-size = 0
icon-size = 0
list-line-height = 25
open-editors-visible = true
palette-width = 500
scale = 1.0
scroll-width = 10
status-height = 25
tab-close-button = "Right"
tab-min-width = 100
tab-separator-height = "Content"
trim-search-results-whitespace = true
